@startuml new_report
actor UsuarioRegistrado
UsuarioRegistrado -> Sistema : Reportar publicación
Sistema -> BaseDeDatos : Guardar reporte
alt 
    Sistema -> Administrador : Notificar administrador
    Administrador -> Sistema : Aprobar o ignorar reporte
    alt Número de reportes >= 3
        Sistema -> BaseDeDatos : Ocultar publicación
        alt Publicaciones automaticas activas
            Sistema -> Publicador : Limita publicación automatica
        else Publicaciones automaticas desactivadas
            Sistema -> Publicador : Es banneado
        end
    else Reporte ignorado
        Sistema -> Publicador : Notificar reporte ignorado
    end
end
@enduml
