@startuml use_cases

left to right direction

actor Usuario
actor Administrador
actor Publicador

rectangle casos {

usecase "Ver publicaciones" as UC_VerPublicaciones
usecase "Registrar asistencia" as UC_RegistrarAsistencia
usecase "Reportar publicación" as UC_ReportarPublicacion
usecase "Ver notificación" as UC_NotificacionEvento
usecase "Crear publicación" as UC_CrearPublicacion
usecase "Aprobar o rechazar publicación" as UC_AprobarRechazarPublicacion
usecase "revisar notificación" as UC_NotificacionAprobacion
UC_RegistrarAsistencia .> UC_NotificacionEvento : genera
UC_ReportarPublicacion .down.> UC_AprobarRechazarPublicacion : requiere aprobación
}

Publicador --> UC_CrearPublicacion
Publicador --> UC_NotificacionAprobacion

Usuario --> UC_NotificacionEvento
Usuario --> UC_VerPublicaciones
Usuario --> UC_RegistrarAsistencia
Usuario --> UC_ReportarPublicacion

Administrador -up-> UC_AprobarRechazarPublicacion



@enduml
